FROM python:3.8.13-slim

# https://github.com/localstack/terraform-local
RUN apt-get update -y && \
    apt-get install -y unzip wget && \
    wget https://releases.hashicorp.com/terraform/1.6.5/terraform_1.6.5_linux_amd64.zip && \
    unzip ./terraform_1.6.5_linux_amd64.zip && \
    ./terraform --version && \
    mv terraform /bin/ && \
    pip install terraform-local==0.16.0

WORKDIR /app

ENV LOCALSTACK_HOSTNAME=localstack \
    S3_HOSTNAME=localstack \
    TF_VAR_s3_use_path_style=true \
    AWS_DEFAULT_REGION=ap-northeast-1

ENTRYPOINT [ "tflocal" ]
