# https://docs.localstack.cloud/getting-started/installation/#docker-compose
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack_main}"
    image: localstack/localstack:3.0.2
    ports:
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=${DEBUG:-0}
      - EXTRA_CORS_ALLOWED_ORIGINS=*
    volumes:
      - type: bind
        source: ${TMPDIR:-/tmp/}localstack
        target: /var/lib/localstack
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock